apiVersion: v1
kind: Secret
metadata:
  name: dvja-secret
  namespace: training
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "ec95c258266b8e985848cae688effa2b"
  MYSQL_USER: "dvja_user"
  MYSQL_PASSWORD: "dvja_password"
